### ISSUE TITLE
📝 新 Macbook Pro 装机记录

### ISSUE THREAD

**Issue by ycjcl868** [ycjcl868/blog#30]
https://www.rustc.cloud/mac-install? 

 手里的一台 MBP 13寸实在是太卡了，被迫换了台新机，记录下新机装机过程。

**Comment by 1c383r9** [comment]
0.o
Test

**Comment by 1c383r9** [comment]
gitalk不登录直接写评论 点发表之后竟然不要求登录~！然后评论就没了··我还以为评论被吞了~

**Comment by ycjcl868** [comment]
> @2ndMessiah
> 0.o
> Test

Gitalk 有些问题，fork 到 blog 仓库里维护了

**Comment by 1c383r9** [comment]
> > @2ndMessiah
> > 0.o
> > Test
> 
> Gitalk 有些问题，fork 到 blog 仓库里维护了

我直接用了Cusdis，不要求登账号，还有评论审核，挺好

**Comment by ycjcl868** [comment]
> > > @2ndMessiah
> > > 0.o
> > > Test
> > 
> > 
> > Gitalk 有些问题，fork 到 blog 仓库里维护了
> 
> 我直接用了Cusdis，不要求登账号，还有评论审核，挺好

之前用过，最大问题是会任意插入广告，而且删不掉

**Comment by ycjcl868** [comment]
> > > @2ndMessiah
> > > 0.o
> > > Test
> > 
> > 
> > Gitalk 有些问题，fork 到 blog 仓库里维护了
> 
> 我直接用了Cusdis，不要求登账号，还有评论审核，挺好

我换成 Cusdis 了，并增加了自动审核通过功能。（`/api/webhook/cusdis`）
