### ISSUE TITLE
Monorepo 下的模块包设计实践

### ISSUE THREAD

**Issue by ycjcl868** [ycjcl868/blog#32]
https://www.rustc.cloud/monorepo-pkg 

 主要面向前端、Node.js 开发者，业务中使用 Monorepo 组织 应用 和 模块，抛砖引玉探讨下：怎样设计一个共享配置包？
UI 组件库怎么打包？怎么使用原生语言（Rust / C++ / Golang 等）编写的模块包？

**Comment by zhengjunxiang** [comment]
多谢分享，干货满满

**Comment by colgin** [comment]
多谢分享，有一个问题，就是障眼法将类型文件指向源文件。我想问下是什么场景需要用这种方法呢？因为我理解无论是 工具库还是组件库都可以在build时生成 类型文件，然后通过types或者typing字段指定就可以了

**Comment by ycjcl868** [comment]
> @colgin
> 多谢分享，有一个问题，就是障眼法将类型文件指向源文件。我想问下是什么场景需要用这种方法呢？因为我理解无论是 工具库还是组件库都可以在build时生成 类型文件，然后通过types或者typing字段指定就可以了

typings 没办法指定多个 entry，比如 `pkg/react` 和 `pkg/vue` 两个入口，typings 没办法分别指定 `/react` 和 `/vue` 的类型。

**Comment by colgin** [comment]
> 

谢谢，我看这个monorepo 的依赖处理的很整洁，想问下，为什么 typescript 这个开发依赖不是放到 根依赖而是放到每个子包里。这里有什么讲究吗？还有这里prettier是在根package.json, 如果项目里使用到了eslint，那么eslint 是放到根依赖还是子包依赖呢？

**Comment by ycjcl868** [comment]
> 

其实也可以放到根 `package.json`

**Comment by ycjcl868** [comment]
> @colgin
> > 
> 
> 谢谢，我看这个monorepo 的依赖处理的很整洁，想问下，为什么 typescript 这个开发依赖不是放到 根依赖而是放到每个子包里。这里有什么讲究吗？还有这里prettier是在根package.json, 如果项目里使用到了eslint，那么eslint 是放到根依赖还是子包依赖呢？

其实也可以放到根 package.json
