### ISSUE TITLE
部署vercel 出现错误

### ISSUE THREAD

**Issue by dashimu** [ycjcl868/blog#34]
出现这个错误，请问怎么修复？谢谢

```

> Build error occurred
--
02:07:32.406 | Error: Failed to collect page data for /page/[page]
02:07:32.406 | at /vercel/path0/node_modules/.pnpm/next@12.2.5_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/next/dist/build/utils.js:743:15
02:07:32.406 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
02:07:32.406 | type: 'Error'
02:07:32.406 | }
02:07:32.435 | ELIFECYCLE  Command failed with exit code 1.
02:07:32.445 | Error: Command "pnpm run build" exited with 1


```

**Comment by dashimu** [comment]
我按照部署步骤，也确认notion 的 page id 是没错的，尝试了几次都出现这个错误。

**Comment by ycjcl868** [comment]
试下添加这两个变量：`NOTION_PAGE_ID`、`NOTION_ACCESS_TOKEN`

<img width="912" alt="image" src="https://user-images.githubusercontent.com/13595509/188366848-c8e05b50-f164-477a-a370-942024ee3859.png">

**Comment by dashimu** [comment]
还是不行。

你博客出现了问题，图片，评论，加载错误。

**Comment by ycjcl868** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/13595509/188611289-1e0da442-c362-4e94-add8-8f01eb7021aa.png">
