### ISSUE TITLE
使用 Vercel + Notion 搭建低成本博客

### ISSUE THREAD

**Issue by ycjcl868** [ycjcl868/blog#35]
https://www.rustc.cloud/blog-dev 

 云时代带来的云成本优势，让个人可以搭建更低成本的博客，成本多低呢？也许你只需要付一个域名的钱。

**Comment by 1c383r9** [comment]
路过～～感谢分享

**Comment by lostornot** [comment]
真不错👍，感觉你改动了很多，还加了侧边的目录，notion自己都不加😊。

**Comment by zfhxi** [comment]
大佬，为啥我用你的这个部署，会显示`APIResponseError: API token is invalid.`，即使我打开notion database的share to web。

**Comment by ycjcl868** [comment]
> 大佬，为啥我用你的这个部署，会显示`APIResponseError: API token is invalid.`，即使我打开notion database的share to web。

`NOTION_ACCESS_TOKEN` 需要注入进去，https://developers.notion.com/docs/create-a-notion-integration

**Comment by 1c383r9** [comment]
信鑫大神~  发现About页面的顶栏的几个按钮位置和普通页面不一样呢~在哪可以调一调？谢谢

**Comment by ycjcl868** [comment]
> @2ndMessiah
> 路过～～感谢分享

修复了

**Comment by ycjcl868** [comment]
> @2ndMessiah
> 信鑫大神~  发现About页面的顶栏的几个按钮位置和普通页面不一样呢~在哪可以调一调？谢谢

修复了

**Comment by zfhxi** [comment]
> > 大佬，为啥我用你的这个部署，会显示`APIResponseError: API token is invalid.`，即使我打开notion database的share to web。
> 
> `NOTION_ACCESS_TOKEN` 需要注入进去，https://developers.notion.com/docs/create-a-notion-integration

大佬，谢谢了，我以为是cookies里的tokenv2，原来是secret开头的Internal Integration Token。。。
